spring:
  datasource:
    url: jdbc:h2:mem:taskdb;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging:
  .level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace 밑에 라이브러리로 대체
# implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.5.6
# org.hibernate.type: trace